# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

[package]
name = "git-cinnabar"
version = "0.6.0-a"
authors = ["Mike Hommey <mh@glandium.org>"]
edition = "2018"
resolver = "2"
license = "MPL-2.0"
repository = "https://github.com/glandium/git-cinnabar"
publish = false

[dependencies]
all_asserts = "2"
bstr = "0.2"
bzip2 = "0.4"
byteorder = "1"
cstr = "0.2"
derivative = "2"
digest = "0.10"
either = "1"
getset = "0.1"
git-version = "0.3"
hex = "0.4"
itertools = "0.10"
libc = "0.2"
once_cell = "1"
percent-encoding = "2"
replace_with = "0.1"
sha-1 = "0.10"
tempfile = "3"
typenum = "1"
url = "2"
which = "4"

[dependencies.array-init]
git = "https://github.com/Manishearth/array-init/"
rev = "cbe9d7e58a52bb43725dbe2ba0cca0755482b3a9"

[dependencies.cinnabar-py]
path = "cinnabar"

[dependencies.clap]
version = "3"
features = ["cargo", "derive"]

[dependencies.curl-sys]
version = "0.4"
default-features = false

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["deref", "display"]

[dependencies.flate2]
version = "1"
default-features = false
features = ["zlib"]

[target.'cfg(windows)'.dependencies.libz-sys]
version = "1"
features = ["static"]

[target.'cfg(not(windows))'.dependencies.libz-sys]
version = "1"

[dependencies.os_pipe]
version = "1.0"
optional = true

[dependencies.semver]
version = "1.0"
optional = true

[dependencies.shared_child]
version = "1.0"
optional = true

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = ["handleapi", "processthreadsapi"]

[dependencies.zstd]
version = "0.10"
default-features = false

[build-dependencies]
cc = "1"
itertools = "0.10"
make-cmd = "0.1"
target = "2.0"

[dev-dependencies]
tempfile = "3"

[profile.release]
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1
panic = "abort"

[features]
default = ["version-check"]
curl-compat = []
version-check = ["os_pipe", "semver", "shared_child"]
